# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'oldtimer.ui'
#
# Created: Thu Sep 15 14:40:02 2011
#      by: pyside-uic 0.2.8 running on PySide 1.0.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(742, 783)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.labelXaxis = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        self.labelXaxis.setFont(font)
        self.labelXaxis.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelXaxis.setObjectName("labelXaxis")
        self.gridLayout.addWidget(self.labelXaxis, 1, 0, 1, 1)
        self.comboXAxisLog = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboXAxisLog.sizePolicy().hasHeightForWidth())
        self.comboXAxisLog.setSizePolicy(sizePolicy)
        self.comboXAxisLog.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboXAxisLog.setObjectName("comboXAxisLog")
        self.gridLayout.addWidget(self.comboXAxisLog, 1, 1, 1, 1)
        self.comboXAxis = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboXAxis.sizePolicy().hasHeightForWidth())
        self.comboXAxis.setSizePolicy(sizePolicy)
        self.comboXAxis.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboXAxis.setObjectName("comboXAxis")
        self.gridLayout.addWidget(self.comboXAxis, 1, 2, 1, 1)
        self.comboYAxis = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboYAxis.sizePolicy().hasHeightForWidth())
        self.comboYAxis.setSizePolicy(sizePolicy)
        self.comboYAxis.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboYAxis.setObjectName("comboYAxis")
        self.gridLayout.addWidget(self.comboYAxis, 0, 2, 1, 1)
        self.comboYAxisLog = QtGui.QComboBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboYAxisLog.sizePolicy().hasHeightForWidth())
        self.comboYAxisLog.setSizePolicy(sizePolicy)
        self.comboYAxisLog.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.comboYAxisLog.setObjectName("comboYAxisLog")
        self.gridLayout.addWidget(self.comboYAxisLog, 0, 1, 1, 1)
        self.labelYaxis = QtGui.QLabel(self.centralwidget)
        self.labelYaxis.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelYaxis.setObjectName("labelYaxis")
        self.gridLayout.addWidget(self.labelYaxis, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelText1 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelText1.sizePolicy().hasHeightForWidth())
        self.labelText1.setSizePolicy(sizePolicy)
        self.labelText1.setText("")
        self.labelText1.setObjectName("labelText1")
        self.gridLayout_2.addWidget(self.labelText1, 0, 0, 1, 1)
        self.labelText2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelText2.sizePolicy().hasHeightForWidth())
        self.labelText2.setSizePolicy(sizePolicy)
        self.labelText2.setText("")
        self.labelText2.setObjectName("labelText2")
        self.gridLayout_2.addWidget(self.labelText2, 0, 1, 1, 1)
        self.textEdit1 = QtGui.QTextEdit(self.centralwidget)
        self.textEdit1.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEdit1.setReadOnly(True)
        self.textEdit1.setObjectName("textEdit1")
        self.gridLayout_2.addWidget(self.textEdit1, 1, 0, 1, 1)
        self.textEdit2 = QtGui.QTextEdit(self.centralwidget)
        self.textEdit2.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.textEdit2.setReadOnly(True)
        self.textEdit2.setObjectName("textEdit2")
        self.gridLayout_2.addWidget(self.textEdit2, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 1, 3, 1)
        self.buttonPlot = QtGui.QPushButton(self.centralwidget)
        self.buttonPlot.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPlot.sizePolicy().hasHeightForWidth())
        self.buttonPlot.setSizePolicy(sizePolicy)
        self.buttonPlot.setObjectName("buttonPlot")
        self.gridLayout_5.addWidget(self.buttonPlot, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 2, 0, 1, 1)
        self.buttonQuit = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonQuit.sizePolicy().hasHeightForWidth())
        self.buttonQuit.setSizePolicy(sizePolicy)
        self.buttonQuit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonQuit.setFlat(False)
        self.buttonQuit.setObjectName("buttonQuit")
        self.gridLayout_5.addWidget(self.buttonQuit, 3, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 742, 25))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Open = QtGui.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.actionE_xit = QtGui.QAction(MainWindow)
        self.actionE_xit.setObjectName("actionE_xit")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.actionE_xit)
        self.menubar.addAction(self.menu_File.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionE_xit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.buttonQuit, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Oldtimer", None, QtGui.QApplication.UnicodeUTF8))
        self.labelXaxis.setText(QtGui.QApplication.translate("MainWindow", "X Axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelYaxis.setText(QtGui.QApplication.translate("MainWindow", "Y Axis:", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPlot.setText(QtGui.QApplication.translate("MainWindow", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionE_xit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))

